### ISSUE TITLE
Ajouter une page 'Sorties à venir'

### ISSUE THREAD

**Issue by CocoBis** [CentraleEgaliteDesChances/website#124]
Faire une page accessible facilement où on pourrai voir la liste des sorties à venir, avec description, date, lieu. Ce qui veux aussi dire créer une entité sortie et un formulaire de création.
Dans un deuxième temps (peut-être pour mon successeur), pouvoir gérer les inscriptions des lycéens directement depuis le site (relation many to many entre lycéen et sortie) et des tuteurs accompagnateurs.

**Comment by TristanPouliquen** [comment]
Module Sorties prochainement disponible avec toutes ces modifs (et plus encore :) )
