### ISSUE TITLE
Pas de message flash sur la liste des sorties

### ISSUE THREAD

**Issue by Imagile** [CentraleEgaliteDesChances/website#139]
Pour le Secteur Sorties, régler le probleme d'affichage des messages flash sur la page des listes de sorties en ajoutant simplement une ligne judicieusement copiée-collée

**Comment by TristanPouliquen** [comment]
J'y ai jeté un oeil. 

Dans la template de base 2-columns du MainBundle, il y a pourtant un affichage prévu via {{session_flash()}}.

**Comment by TristanPouliquen** [comment]
J'ai trouvé le probleme. Dans les templates du bundle Sorties, il manque un {{parent()}} dans les blocks pour faire apparaitre ces messages flash.

Probleme réglé.
