### ISSUE TITLE
Remeber me

### ISSUE THREAD

**Issue by Imagile** [CentraleEgaliteDesChances/website#140]
On pourrait ajouter l'option "se souvenir de moi" au formulaire de connexion.
Ca n'a pas l'air très compliqué : http://symfony.com/doc/current/cookbook/security/remember_me.html

**Comment by j2bbayle** [comment]
:+1: Bonne idée ! Ce n'est en effet pas difficile.

**Comment by TristanPouliquen** [comment]
Dans le bundle Security de Symfony, j'ai vu trainer une classe appelée RememberMe. Ca doit pouvoir se mettre en place tout seul :)

**Comment by TristanPouliquen** [comment]
Option mise en place.
